### PR TITLE
Edited and added new stuff

### PR DESCRIPTION
**Pull request by alielkline**
[Edited] the booking history table
[added] 2 new functions to cancel and reschedule an appointment

### CODE REVIEW

**Comment by KhaledMoFA** [comment]
الشغل ده مش عاجبني

**Comment by alielkline** [comment]
خليك في شغلك بعد أذنك

**Comment by KhaledMoFA** [comment]
هحترمك علشان انت راجل صاحب جداول وترابيزات

**Review by mohammed893 — CHANGES_REQUESTED** [review]
You can set variables like slot_start_time at the beginning of the function since they’re used across multiple sub-queries. More importantly, wrap each function in a transaction block to ensure that no changes are made to the database unless all operations succeed.

**Review by mohammed893 — APPROVED** [review]

**Pull request merged**
